Repository olech2412/DB-Adapter-v6, pull requests merged in 2024-01, with the labels that each got.

#3 1 allow to add custom parameters to every request
  src/main/java/de/olech2412/adapter/dbadapter/APIConfiguration.java
  src/main/java/de/olech2412/adapter/dbadapter/DB_Adapter_v6.java
  src/main/java/de/olech2412/adapter/dbadapter/request/Request.java
  src/main/java/de/olech2412/adapter/dbadapter/request/parameters/Parameter.java
  src/main/java/de/olech2412/adapter/dbadapter/request/parameters/ParameterEvaluator.java
  src/main/java/de/olech2412/adapter/dbadapter/request/parameters/RequestParametersNames.java
  src/test/java/de/olech2412/adapter/dbadapter/APIConfigurationTest.java
  src/test/java/de/olech2412/adapter/dbadapter/DB_Adapter_v6Test.java
  src/test/java/de/olech2412/adapter/dbadapter/request/parameters/ParameterEvaluatorTest.java
  src/test/java/de/olech2412/adapter/dbadapter/request/parameters/ParameterTest.java
  src/test/java/de/olech2412/adapter/dbadapter/request/parameters/RequestParametersNamesTest.java
Labels: feature, development

#4 Update Build-Test-Pipeline.yml
  .github/workflows/Build-Test-Pipeline.yml
Labels: development

#7 new version due to fundamental usage changes
  pom.xml
Labels: feature, development

#8 added README.md
  README.md
Labels: documentation

#10 9 add new parameters
  src/main/java/de/olech2412/adapter/dbadapter/request/parameters/RequestParametersNames.java
  src/test/java/de/olech2412/adapter/dbadapter/DB_Adapter_v6Test.java
  src/test/java/de/olech2412/adapter/dbadapter/gsonadapter/LocalDateTimeAdapterTest.java
Labels: feature

#12 added link for https://github.com/derhuerst
  README.md
Labels: enhancement
